### ISSUE TITLE
Error when displaying downloaded images

### ISSUE THREAD

**Issue by darioflute** [darioflute/sospex#2]
After downloading an image from science archives, the program emits a series of
errors when displaying it. This is the traceback:

Traceback (most recent call last):
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 155, in __draw_idle_agg
    self.draw()
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 127, in draw
    super(FigureCanvasQTAggBase, self).draw()
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 322, in draw
    self.apply_aspect()
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1430, in apply_aspect
    pb1 = pb.shrunk_to_aspect(box_aspect, pb, fig_aspect)
  File "/Users/dfadda/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 604, in shrunk_to_aspect
    raise ValueError("'box_aspect' and 'fig_aspect' must be positive")
ValueError: 'box_aspect' and 'fig_aspect' must be positive

The issue does not exist in Ubuntu Linux.

**Comment by darioflute** [comment]
Similar issue at this URL:
https://github.com/scikit-image/scikit-image/issues/2094

It is probably a problem of qt5agg.
Even updating Qt to the latest distribution (5.9.2) does not resolve the problem.

**Comment by darioflute** [comment]
The error happens only in the case there is only one image tab open at the beginning.
To avoid it, I added M0 as 2nd tab when opening GREAT images.
